name: Deploy (Docker to VPS)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ai-finance-platform:latest

      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            mkdir -p ~/app
            cd ~/app
            if [ ! -f docker-compose.yml ]; then
              cat > docker-compose.yml <<'YAML'
            services:
              web:
                image: ${DOCKER_USERNAME}/ai-finance-platform:latest
                ports:
                  - "3000:3000"
                env_file:
                  - .env
                restart: unless-stopped
            YAML
            fi
            if [ ! -f .env ] && [ -n "${APP_ENV}" ]; then
              echo "$APP_ENV" > .env
            fi
            docker pull ${DOCKER_USERNAME}/ai-finance-platform:latest
            docker compose up -d --remove-orphans
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          APP_ENV: ${{ secrets.APP_ENV }}


